import moment from 'moment';

const daos =
[
    {
      daoName: 'Lizax',
      daoWebsite: 'lizax.com',
      daoDescription: 'Lizax is the first DAO to revolutionize the gaming business.',
      dmrReward: 200,
      financePoints: 30,
      productPoints: 50,
      orgPoints: 40,
      partnerPoints: 10,
      minPartic: 15,
      decidingPercentage: 50,
      minVoting: 20,
      maxVoting: 50,
      tokenName: 'LizaxToken',
      tickerSymbol: 'LZX',
      totalSupply: 15000,
      selectedCurrency: 'finney',
      minPrice: 20000,
      maxPrice: 23500,
      saleStart: moment("20171206", "YYYYMMDD").format('LL'),
      saleEnd: moment("20171212", "YYYYMMDD").format('LL'),
      shTokens: 478,
      totalAddresses: 60
    },
    {
      daoName: 'TorX',
      daoWebsite: 'TorX.com',
      daoDescription: 'TorX is the first DAO to revolutionize the gaming business.',
      dmrReward: 200,
      financePoints: 30,
      productPoints: 50,
      orgPoints: 40,
      partnerPoints: 10,
      minPartic: 15,
      decidingPercentage: 50,
      minVoting: 20,
      maxVoting: 50,
      tokenName: 'TorXToken',
      tickerSymbol: 'TRX',
      totalSupply: 9000,
      selectedCurrency: 'finney',
      minPrice: 20000,
      maxPrice: 23500,
      saleStart: moment("20171206", "YYYYMMDD").format('LL'),
      saleEnd: moment("20171212", "YYYYMMDD").format('LL'),
      shTokens: 235,
      totalAddresses: 23
    },
    {
      daoName: 'Mint',
      daoWebsite: 'Mint.com',
      daoDescription: 'Mint is the first DAO to revolutionize the gaming business.',
      dmrReward: 200,
      financePoints: 30,
      productPoints: 50,
      orgPoints: 40,
      partnerPoints: 10,
      minPartic: 15,
      decidingPercentage: 50,
      minVoting: 20,
      maxVoting: 50,
      tokenName: 'MintToken',
      tickerSymbol: 'MNT',
      totalSupply: 18000,
      selectedCurrency: 'finney',
      minPrice: 20000,
      maxPrice: 23500,
      saleStart: moment("20171206", "YYYYMMDD").format('LL'),
      saleEnd: moment("20171212", "YYYYMMDD").format('LL'),
      shTokens: 780,
      totalAddresses: 31
    },
    {
      daoName: 'Zeltox',
      daoWebsite: 'Zeltox.com',
      daoDescription: 'Zeltox is the first DAO to revolutionize the gaming business.',
      dmrReward: 200,
      financePoints: 30,
      productPoints: 50,
      orgPoints: 40,
      partnerPoints: 10,
      minPartic: 15,
      decidingPercentage: 50,
      minVoting: 20,
      maxVoting: 50,
      tokenName: 'ZeltoxToken',
      tickerSymbol: 'ZTX',
      totalSupply: 50000,
      selectedCurrency: 'finney',
      minPrice: 18000,
      maxPrice: 23500,
      saleStart: moment("20171206", "YYYYMMDD").format('LL'),
      saleEnd: moment("20171212", "YYYYMMDD").format('LL'),
      shTokens: 130,
      totalAddresses: 80
    },
  ]

  export default daos;