import moment from 'moment';

const polls =
[
    {
        daoName: 'Lizax',
        polls: [
            {
                header: 'Issue 99 CVS shares',
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 8,
                addressesAgainst: 1,
                tokensFor: 250,
                tokensAgainst: 30,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'active'
            },
            {
                header: 'Create a stock sale to raise 10 ETH at 0.1 ETH per CVS share',
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 10,
                addressesAgainst: 8,
                tokensFor: 300,
                tokensAgainst: 120,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'active'
            },
            {
                header: "For Begin stock sale a minimum status of 'executive' will be needed",
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 2,
                addressesAgainst: 1,
                tokensFor: 70,
                tokensAgainst: 30,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'active'
            },
            {
                header: 'Create a stock sale to raise 50 ETH at 0.1 ETH per CVS share',
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 3,
                addressesAgainst: 1,
                tokensFor: 97,
                tokensAgainst: 31,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'active'
            },
            {
                header: 'Create a stock sale to raise 1000 ETH at 0.1 ETH per CVS share',
                endDate: moment("20171207", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 3,
                addressesAgainst: 1,
                tokensFor: 97,
                tokensAgainst: 31,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'completed'
            },
            {
                header: 'Create a stock sale to raise 300 ETH at 0.1 ETH per CVS share',
                endDate: moment("20171206", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 3,
                addressesAgainst: 1,
                tokensFor: 97,
                tokensAgainst: 31,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'completed'
            },
            {
                header: 'Create a stock sale to raise 50 ETH at 0.5 ETH per CVS share',
                endDate: moment("20171205", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 3,
                addressesAgainst: 1,
                tokensFor: 97,
                tokensAgainst: 31,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'completed'
            },
        ]
    },
    {
        daoName: 'TorX',
        polls: [
            {
                header: 'Issue 88 CVS shares',
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 8,
                addressesAgainst: 1,
                tokensFor: 250,
                tokensAgainst: 30,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'active'
            },
            {
                header: 'Create a stock sale to raise 10 ETH at 0.1 ETH per CVS share',
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 10,
                addressesAgainst: 8,
                tokensFor: 300,
                tokensAgainst: 120,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'active'
            },
            {
                header: "For Begin stock sale a minimum status of 'executive' will be needed",
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 2,
                addressesAgainst: 1,
                tokensFor: 70,
                tokensAgainst: 30,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'active'
            },
            {
                header: 'Create a stock sale to raise 50 ETH at 0.1 ETH per CVS share',
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 3,
                addressesAgainst: 1,
                tokensFor: 97,
                tokensAgainst: 31,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'active'
            },
            {
                header: 'Create a stock sale to raise 1000 ETH at 0.1 ETH per CVS share',
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 3,
                addressesAgainst: 1,
                tokensFor: 97,
                tokensAgainst: 31,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'completed'
            },
            {
                header: 'Create a stock sale to raise 300 ETH at 0.1 ETH per CVS share',
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 3,
                addressesAgainst: 1,
                tokensFor: 97,
                tokensAgainst: 31,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'completed'
            },
            {
                header: 'Create a stock sale to raise 50 ETH at 0.5 ETH per CVS share',
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 3,
                addressesAgainst: 1,
                tokensFor: 97,
                tokensAgainst: 31,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'completed'
            },
        ]
    },
    {
        daoName: 'Mint',
        polls: [
            {
                header: 'Issue 77 CVS shares',
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 8,
                addressesAgainst: 1,
                tokensFor: 250,
                tokensAgainst: 30,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'active'
            },
            {
                header: 'Create a stock sale to raise 10 ETH at 0.1 ETH per CVS share',
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 10,
                addressesAgainst: 8,
                tokensFor: 300,
                tokensAgainst: 120,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'active'
            },
            {
                header: "For Begin stock sale a minimum status of 'executive' will be needed",
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 2,
                addressesAgainst: 1,
                tokensFor: 70,
                tokensAgainst: 30,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'active'
            },
            {
                header: 'Create a stock sale to raise 50 ETH at 0.1 ETH per CVS share',
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 3,
                addressesAgainst: 1,
                tokensFor: 97,
                tokensAgainst: 31,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'active'
            },
            {
                header: 'Create a stock sale to raise 1000 ETH at 0.1 ETH per CVS share',
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 3,
                addressesAgainst: 1,
                tokensFor: 97,
                tokensAgainst: 31,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'completed'
            },
            {
                header: 'Create a stock sale to raise 300 ETH at 0.1 ETH per CVS share',
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 3,
                addressesAgainst: 1,
                tokensFor: 97,
                tokensAgainst: 31,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'completed'
            },
            {
                header: 'Create a stock sale to raise 50 ETH at 0.5 ETH per CVS share',
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 3,
                addressesAgainst: 1,
                tokensFor: 97,
                tokensAgainst: 31,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'completed'
            },
        ]
    },
    {
        daoName: 'Zeltox',
        polls: [
            {
                header: 'Issue 55 CVS shares',
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 8,
                addressesAgainst: 1,
                tokensFor: 250,
                tokensAgainst: 30,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'active'
            },
            {
                header: 'Create a stock sale to raise 10 ETH at 0.1 ETH per CVS share',
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 10,
                addressesAgainst: 8,
                tokensFor: 300,
                tokensAgainst: 120,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'active'
            },
            {
                header: "For Begin stock sale a minimum status of 'executive' will be needed",
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 2,
                addressesAgainst: 1,
                tokensFor: 70,
                tokensAgainst: 30,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'active'
            },
            {
                header: 'Create a stock sale to raise 50 ETH at 0.1 ETH per CVS share',
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 3,
                addressesAgainst: 1,
                tokensFor: 97,
                tokensAgainst: 31,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'active'
            },
            {
                header: 'Create a stock sale to raise 1000 ETH at 0.1 ETH per CVS share',
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 3,
                addressesAgainst: 1,
                tokensFor: 97,
                tokensAgainst: 31,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'completed'
            },
            {
                header: 'Create a stock sale to raise 300 ETH at 0.1 ETH per CVS share',
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 3,
                addressesAgainst: 1,
                tokensFor: 97,
                tokensAgainst: 31,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'completed'
            },
            {
                header: 'Create a stock sale to raise 50 ETH at 0.5 ETH per CVS share',
                endDate: moment("20171210", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 3,
                addressesAgainst: 1,
                tokensFor: 97,
                tokensAgainst: 31,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'completed'
            },
        ]
    },
    {
        daoName: 'EBike Enterprises',
        polls: [
            {
                header: 'Change decision maker reward for product to 10eth/quarter starting Q2 2018',
                endDate: moment("20171212", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 9,
                addressesAgainst: 4,
                tokensFor: 549,
                tokensAgainst: 230,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'organisation',
                state: 'active'
            },
            {
                header: 'Switch to battery Tesla 48V 35Ah 1000W Li-Ion',
                endDate: moment("20171213", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 10,
                addressesAgainst: 8,
                tokensFor: 512,
                tokensAgainst: 340,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'product',
                state: 'active'
            },
            {
                header: 'Offer bike in additional color #992020',
                endDate: moment("20171213", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 7,
                addressesAgainst: 3,
                tokensFor: 300,
                tokensAgainst: 220,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'product',
                state: 'active'
            },
            {
                header: 'Offer free Strava bike app with every bike for 150eth',
                endDate: moment("20171214", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 3,
                addressesAgainst: 1,
                tokensFor: 130,
                tokensAgainst: 50,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'partnership',
                state: 'active'
            },
            {
                header: 'Change company Logo (see attachment)',
                endDate: moment("20171205", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 10,
                addressesAgainst: 8,
                tokensFor: 459 ,
                tokensAgainst: 300,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'product',
                state: 'completed'
            },
            {
                header: 'Pay out 100 eth in dividend in Beginning of Q3',
                endDate: moment("20171207", "YYYYMMDD").format('LL'),
                description: 'More information on the voting',
                addressesFor: 14,
                addressesAgainst: 4,
                tokensFor: 623,
                tokensAgainst: 240,
                voterAddresses: [],
                payout: '2000 finney',
                category: 'finance',
                state: 'completed'
            },
        ]
    },
]

export default polls;
